// src/context/CardsContext.js

import React, { createContext, useState, useEffect } from 'react';

export const ReviewContext = createContext();

export function ReviewContextProvider({ children }) {
  // Function to get initial state from sessionStorage or use default
  const getInitialReviews = () => {
    const storesReviews = sessionStorage.getItem('reviews');
    if (storesReviews) {
      try {
        return JSON.parse(storesReviews);
      } catch (error) {
        console.error(
          'Error parsing storesReviews from sessionStorage:',
          error,
        );
        // If parsing fails, return default cards
      }
    }

    // Default cards data
    return [
      // Job ID 1 reviews
      {
        id: 1,
        jobId: 1,
        workLifeBalance: 4,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 2,
        impactfulness: 5,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 2,
        independenceCollaboration: 5,
      },
      {
        id: 2,
        jobId: 1,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 3,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 3,
        jobId: 1,
        workLifeBalance: 5,
        creativity: 5,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 5,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 5,
        creativityAnalytical: 2,
        independenceCollaboration: 5,
      },
      {
        id: 4,
        jobId: 1,
        workLifeBalance: 3,
        creativity: 4,
        professionalDevelopment: 2,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 3,
        sustainability: 2,
        recognitionAndAppreciation: 3,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 5,
        jobId: 1,
        workLifeBalance: 2,
        creativity: 3,
        professionalDevelopment: 2,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 4,
        transparentCommunication: 3,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 3,
      },
      {
        id: 6,
        jobId: 1,
        workLifeBalance: 3,
        creativity: 3,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 4,
        creativityAnalytical: 2,
        independenceCollaboration: 4,
      },
      {
        id: 7,
        jobId: 1,
        workLifeBalance: 4,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 5,
        impactfulness: 4,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 8,
        jobId: 1,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 3,
        socialWorkEnvironment: 3,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 3,
      },
      {
        id: 9,
        jobId: 1,
        workLifeBalance: 3,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 3,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 2,
        independenceCollaboration: 4,
      },
      {
        id: 10,
        jobId: 1,
        workLifeBalance: 2,
        creativity: 3,
        professionalDevelopment: 2,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 2,
        impactfulness: 4,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },

      // Job ID 2 reviews
      {
        id: 11,
        jobId: 2,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 3,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 12,
        jobId: 2,
        workLifeBalance: 3,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 2,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 5,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 13,
        jobId: 2,
        workLifeBalance: 5,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 14,
        jobId: 2,
        workLifeBalance: 3,
        creativity: 4,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 3,
        transparentCommunication: 3,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 4,
        independenceCollaboration: 4,
      },
      {
        id: 15,
        jobId: 2,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 3,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 16,
        jobId: 2,
        workLifeBalance: 5,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 5,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 17,
        jobId: 2,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 2,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 5,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 18,
        jobId: 2,
        workLifeBalance: 3,
        creativity: 3,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 5,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 4,
      },
      {
        id: 19,
        jobId: 2,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 5,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 3,
        transparentCommunication: 4,
        socialWorkEnvironment: 5,
        routineVariability: 5,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 20,
        jobId: 2,
        workLifeBalance: 3,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },

      // Job ID 3 reviews
      {
        id: 21,
        jobId: 3,
        workLifeBalance: 5,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 22,
        jobId: 3,
        workLifeBalance: 4,
        creativity: 3,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 5,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 5,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 23,
        jobId: 3,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 4,
        independenceCollaboration: 4,
      },
      {
        id: 24,
        jobId: 3,
        workLifeBalance: 3,
        creativity: 3,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 25,
        jobId: 3,
        workLifeBalance: 5,
        creativity: 4,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 4,
        impactfulness: 5,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 3,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 26,
        jobId: 3,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 5,
        impactfulness: 4,
        sustainability: 3,
        recognitionAndAppreciation: 3,
        transparentCommunication: 4,
        socialWorkEnvironment: 5,
        routineVariability: 5,
        creativityAnalytical: 2,
        independenceCollaboration: 4,
      },
      {
        id: 27,
        jobId: 3,
        workLifeBalance: 5,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 4,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 3,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 2,
        independenceCollaboration: 4,
      },
      {
        id: 28,
        jobId: 3,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 3,
        impactfulness: 3,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 5,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 29,
        jobId: 3,
        workLifeBalance: 4,
        creativity: 3,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 5,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 5,
        creativityAnalytical: 2,
        independenceCollaboration: 5,
      },
      {
        id: 30,
        jobId: 3,
        workLifeBalance: 3,
        creativity: 5,
        professionalDevelopment: 2,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 2,
        impactfulness: 3,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      // Job ID 4 reviews
      {
        id: 31,
        jobId: 4,
        workLifeBalance: 4,
        creativity: 3,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 5,
        sustainability: 3,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 32,
        jobId: 4,
        workLifeBalance: 3,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 3,
        transparentCommunication: 3,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 33,
        jobId: 4,
        workLifeBalance: 5,
        creativity: 5,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 5,
        sustainability: 3,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 5,
        creativityAnalytical: 2,
        independenceCollaboration: 4,
      },
      {
        id: 34,
        jobId: 4,
        workLifeBalance: 3,
        creativity: 4,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 3,
        sustainability: 2,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 35,
        jobId: 4,
        workLifeBalance: 2,
        creativity: 3,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 2,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 3,
        transparentCommunication: 4,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 36,
        jobId: 4,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 37,
        jobId: 4,
        workLifeBalance: 5,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 5,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 5,
        routineVariability: 5,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 38,
        jobId: 4,
        workLifeBalance: 3,
        creativity: 3,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 3,
        transparentCommunication: 3,
        socialWorkEnvironment: 3,
        routineVariability: 4,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 39,
        jobId: 4,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 3,
        sustainability: 3,
        recognitionAndAppreciation: 5,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 40,
        jobId: 4,
        workLifeBalance: 3,
        creativity: 5,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 3,
        socialWorkEnvironment: 3,
        routineVariability: 5,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },

      // Job ID 5 reviews
      {
        id: 41,
        jobId: 5,
        workLifeBalance: 4,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 42,
        jobId: 5,
        workLifeBalance: 5,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 3,
        recognitionAndAppreciation: 3,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 3,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 43,
        jobId: 5,
        workLifeBalance: 3,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 5,
        impactfulness: 4,
        sustainability: 5,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 5,
        creativityAnalytical: 4,
        independenceCollaboration: 3,
      },
      {
        id: 44,
        jobId: 5,
        workLifeBalance: 4,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 3,
        impactfulness: 4,
        sustainability: 3,
        recognitionAndAppreciation: 5,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 45,
        jobId: 5,
        workLifeBalance: 3,
        creativity: 3,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 5,
        sustainability: 5,
        recognitionAndAppreciation: 3,
        transparentCommunication: 3,
        socialWorkEnvironment: 4,
        routineVariability: 5,
        creativityAnalytical: 4,
        independenceCollaboration: 5,
      },
      {
        id: 46,
        jobId: 5,
        workLifeBalance: 5,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 5,
        impactfulness: 3,
        sustainability: 4,
        recognitionAndAppreciation: 4,
        transparentCommunication: 5,
        socialWorkEnvironment: 5,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 47,
        jobId: 5,
        workLifeBalance: 4,
        creativity: 3,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 4,
        recognitionAndAppreciation: 5,
        transparentCommunication: 4,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
      {
        id: 48,
        jobId: 5,
        workLifeBalance: 3,
        creativity: 4,
        professionalDevelopment: 4,
        inclusivityAndDiversity: 3,
        mentalHealthSupport: 3,
        impactfulness: 5,
        sustainability: 4,
        recognitionAndAppreciation: 3,
        transparentCommunication: 5,
        socialWorkEnvironment: 4,
        routineVariability: 5,
        creativityAnalytical: 2,
        independenceCollaboration: 5,
      },
      {
        id: 49,
        jobId: 5,
        workLifeBalance: 4,
        creativity: 5,
        professionalDevelopment: 3,
        inclusivityAndDiversity: 4,
        mentalHealthSupport: 4,
        impactfulness: 4,
        sustainability: 3,
        recognitionAndAppreciation: 5,
        transparentCommunication: 3,
        socialWorkEnvironment: 4,
        routineVariability: 4,
        creativityAnalytical: 3,
        independenceCollaboration: 5,
      },
      {
        id: 50,
        jobId: 5,
        workLifeBalance: 5,
        creativity: 4,
        professionalDevelopment: 5,
        inclusivityAndDiversity: 5,
        mentalHealthSupport: 3,
        impactfulness: 3,
        sustainability: 5,
        recognitionAndAppreciation: 4,
        transparentCommunication: 4,
        socialWorkEnvironment: 5,
        routineVariability: 3,
        creativityAnalytical: 3,
        independenceCollaboration: 4,
      },
    ];
  };

  const [reviews, setReviews] = useState(getInitialReviews());

  useEffect(() => {
    sessionStorage.setItem('reviews', JSON.stringify(reviews));
  }, [reviews]);  

  return (
    <ReviewContext.Provider value={{ reviews }}>
      {children}
    </ReviewContext.Provider>
  );
}
